export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export var CHANGE_TAB = "CHANGE_TAB";

export const CHAPTERS_FETCH_BEGIN = "CHAPTERS_FETCH_BEGIN";
export const CHAPTERS_FETCH_SUCCESS = "CHAPTERS_FETCH_SUCCESS";
export const CHAPTERS_FETCH_FAILURE = "CHAPTERS_FETCH_FAILURE";
