export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export var CHANGE_TAB = "CHANGE_TAB";

export const CHAPTERS_FETCH_BEGIN = "CHAPTERS_FETCH_BEGIN";
export const CHAPTERS_FETCH_SUCCESS = "CHAPTERS_FETCH_SUCCESS";
export const CHAPTERS_FETCH_FAILURE = "CHAPTERS_FETCH_FAILURE";

export const USERS_FETCH_BEGIN = "USERS_FETCH_BEGIN";
export const USERS_FETCH_SUCCESS = "USERS_FETCH_SUCCESS";
export const USERS_FETCH_FAILURE = "USERS_FETCH_FAILURE";

export const UPDATE_CREDIT_BEGIN = "UPDATE_CREDIT_BEGIN";
export const UPDATE_CREDIT_SUCCESS = "UPDATE_CREDIT_SUCCESS";
export const UPDATE_CREDIT_FAILURE = "UPDATE_CREDIT_FAILURE";

export const UPDATE_CHAPTER_BEGIN = "UPDATE_CHAPTER_BEGIN";
export const UPDATE_CHAPTER_SUCCESS = "UPDATE_CHAPTER_SUCCESS";
export const UPDATE_CHAPTER_FAILURE = "UPDATE_CHAPTER_FAILURE";

export const REMOVE_CHAPTER_BEGIN = "REMOVE_CHAPTER_BEGIN";
export const REMOVE_CHAPTER_SUCCESS = "REMOVE_CHAPTER_SUCCESS";
export const REMOVE_CHAPTER_FAILURE = "REMOVE_CHAPTER_FAILURE";
